
## Input files ##
# Path to reference fasta file. 
ref_path: "../data/VariantHunter_input/ResFinder_20200125"

# Path to list of sample names. One line per name.
sample_name_path: "../data/VariantHunter_input/gs2_sample_names_exclude_62.txt"

# Path to folder with trimmed illumina paired end fastq sequences 
seq_path: "/home/projects/cge/data/projects/5001/Sewage_data_symbolic_links/Trimmed/"

# What comes after sample name for singletons
singleton_suf: "_R1.singletons.fq.gz"

# What comes after sample name for forwar og reverse reads. Use * to indicate a 1 or a 2.
for_rev_suf: "_R*.trim.fq.gz"


## Mapping ##

# ConClave version, Choose "1" or "2"
conclave_verson: "2"

# Choose alignment parameters for kma mapping software. 
# Suggestion: "-reward 1 -penalty -3 -gapopen -5 -gapextend -1 -per 17 -mrs 0.75"
# If defalt are wanted choose: ""
# If settings tested ideal for ResFinder database is wanted choose: "-cge" 
alignment_setting_for_kma:  "-cge"


## Variant Calling ##

# Do not even consider ALT allele if proportion of ref allele is equal to or more than given value. E.g. "0.5"
p_value: "0.75"

# Include "orphan" reads, where the mate is not paired? For yes choose "-A" , for no choose "".
orphan_reads: "-A"

# Choose ploidy for samples. Choose "1" for haploid. 
# See http://samtools.github.io/bcftools/bcftools.html#call for more options.
ploidy: "1"


# minimum base quality
minimum_base_Q: "15"

# minimum mapping quality
minimum_map_Q: "10"

# minimum proportion of  forward and reverse for ALT  alleles. Suggested value 0.2  
minimum_ALT_strand_prop_forward_and_reverse: "0.2"

# minimum allele depth for non-reference allele for the call to be accepted
minimum_ALT_AD: "5"

# minimum allele frequency for non-reference allele for the call to be accepted
minimum_ALT_AF: "0.75"


## Consensus Sequence quality filtering ##

# minimum template coverage in percent, in order to accept the consensus sequence as "high coverage" and keep it 
min_template_cov: "97"

# Minimum mean depth
min_meandepth: "7" 

# Percentage unknown nucleotides "N" allowed. 
# N can mean that the position did not get through the vcf filtering 
# or the position was not found in the vcf file due to problems with coverage or bcftools
percentage_unknown_nuc_allowed: "1"


## Clustering ##
# Read the documentation to choose correct wordsize for the cluster_identity!  
# https://github.com/weizhongli/cdhit/wiki/3.-User's-Guide#CDHITEST

cluster_identity_cd_hit: "0.95"
cluster_wordsize_cd_hit: "9"

# Choose at least "2" for minimum cluster size.
minimum_cluster_size: "2"
